### ISSUE TITLE
온보딩

### ISSUE THREAD

**Issue by TaeseongYun** [Nexters/Full-Stack-Android#34]

**Comment by TaeseongYun** [comment]
@gowoon-choi 혹쉬 이번 온보딩 진행할 때 SharedPreference 말고 DataStore 사용해보는건 어떨까요 ?
이미 SharedPreference 로 개발이 진행되었다면 그대로 가요 ~

[참고자료 - Hello DataStore](https://medium.com/scalereal/hello-datastore-bye-sharedpreferences-android-f46c610b81d5)

**Comment by gowoon-choi** [comment]
오 안그래도 저도 DataStore 사용해보려고 하고 있었슴니당 ! 의견 감사해유

**Comment by gowoon-choi** [comment]
@TaeseongYun 이거 DataStore로 짜면서 좀 이상해서 요래 저래 고생하고 좀 찾아봤는데, DataStore 자체가 coroutine, flow로 비동기로 되어있어서 isFirst를 업데이트 하면 그걸 인식해서 다시 데이터를 읽게 됩니다 ! 그래서 onboarding에는 적절하지 않다고 합니다 ! 알아두면 좋을 거 같아서 공유합니다 !!

**Comment by TaeseongYun** [comment]
isFirst 라는 변수가 DataStore 내부에 있는 변수인거죠 ?
참고자료도 같이 받아볼 수 있을까요 ?

**Comment by gowoon-choi** [comment]
SharedPreference에서도 처음 들어온건지 아닌지 isFirst를 키-밸류로 키-불린 이런식으루 관리하자나유 ! Preference dataStore도 비슷한 방식인데 반응형으로 비동기로 처리될 수 있도록 되어있도라구요 ! 구래서 읽으려면 플로우로 반환받고 업데이트도 서스펜드로 선언에서 코루틴에서 호출하게끔 ! 그래서 온보딩에서도 상황에 따라서 쓸 수 있기도 하고 없기도 해서 제가 슬랙에 어떤 시점에서 preference에 boolean 업데이트를 해줘ㅇㅑ하나 그거에 따라서 datastore 사용이 결정될 거 같아서 물어봤는데 ! 답변 받아보니까 datastore 사용 가능할 고 같아서 다시 해보는중 ! 오늘안에 마무리해서 pr 쏠게 읽어봐조유 ! 글구 datastore관련 자료들은 내가 본 것들이랑 직접 개발해보면서 알게된 것들 정리해서 공유해줄게요 !

**Comment by gowoon-choi** [comment]
주절주절..🧐
